import type { components } from './schema'

export type ApiSchemas = components['schemas']
export type ApiErrorEnvelope = ApiSchemas['ErrorResponse']
export type ApiErrorBody = ApiSchemas['Error']
export type AuthContext = ApiSchemas['AuthContext']
export type AdminUser = ApiSchemas['AdminUser']
export type Permission = ApiSchemas['Permission']
export type Overview = ApiSchemas['Overview']
export type DashboardMetric = ApiSchemas['DashboardMetric']
export type OverviewTrendPoint = ApiSchemas['OverviewTrendPoint']
export type AdminEvent = ApiSchemas['AdminEvent']
export type EventTopic = ApiSchemas['EventTopic']
export type EventType = ApiSchemas['EventType']
export type Group = ApiSchemas['Group']
export type GroupList = ApiSchemas['GroupList']
export type GroupRole = ApiSchemas['GroupRole']
export type GroupSyncResult = ApiSchemas['GroupSyncResult']
export type FeatureKey = ApiSchemas['FeatureKey']
export type FeatureSettings = ApiSchemas['FeatureSettings']
export type GlobalSettings = ApiSchemas['GlobalSettings']
export type GlobalSettingsPatch = ApiSchemas['GlobalSettingsPatch']
export type GroupFeatureOverrides = ApiSchemas['GroupFeatureOverrides']
export type GroupSettings = ApiSchemas['GroupSettings']
export type GroupSettingsPatch = ApiSchemas['GroupSettingsPatch']
